/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.tvt.swing;

import com.tvt.entity.Model_Menu;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/**
 *
 * @author ASUS
 */
public class Menu_Item extends javax.swing.JPanel {

    /**
     * Creates new form Menu_Item
     */
    private boolean selected;
    
    public Menu_Item(Model_Menu data) {
        initComponents();
        setOpaque(false);
       if (data.getType() == Model_Menu.MenuType.MENU) {
            lblNameMenu.setText(data.getName());
            lblNameMenu.setFont(new Font("Segoe UI", Font.PLAIN, 14)); 
        } else if (data.getType() == Model_Menu.MenuType.TITLE) {
            lblNameMenu.setText(data.getName());
            lblNameMenu.setFont(new Font("Segoe UI", Font.BOLD, 16)); 
        } else {
            lblNameMenu.setText("");
        }
    }

    public void setSelected(boolean selected) {
        this.selected = selected;
        repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNameMenu = new javax.swing.JLabel();

        lblNameMenu.setForeground(new java.awt.Color(255, 255, 255));
        lblNameMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNameMenu.setText("Menu Item");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNameMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNameMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics g) {
        if(selected){
            Graphics2D g2 = (Graphics2D) g;
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            g2.setColor(new Color(255,255,255,80));
            g2.fillRoundRect(10, 0, getWidth() - 20, getHeight(), 5, 5);
        }
        super.paintComponent(g); 
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblNameMenu;
    // End of variables declaration//GEN-END:variables

    /**
     * @param selected the selected to set
     */
}
